name: textnn
channels:
  - defaults
  - conda-forge
dependencies:
  - keras=2.2.4
  - pytest=4.2.0
  - scikit-learn=0.20.0
  - tensorflow=1.12.0
  - fire=0.1.3
  # optional: for plotting training progress
  - matplotlib=3.0.2
